image: docker:18.06.3


variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  # - deploy

default:
  before_script:
    - pulumi login s3://carpedalan-pulumi
    - pulumi stack select dev

cache:
  key: docker-cache
  paths:
    - api.tar
    - client.tar

build client:
  before_script:
    - echo 'Skipping login'
  stage: build
  services:
    - docker:18.06.3-dind
  cache:
    key: client-cache
    paths:
      - client.tar
  artifacts: 
    expire_in: 1 week
    paths: 
      - client.tar
  script: 
    - ls -al
    - '[ -f ./client.tar ] && docker load --input client.tar'
    - docker build -t client:latest -f client/Dockerfile --cache-from client:latest --cache-from node:12-slim ./client
    - docker save client:latest > client.tar
build api:
  before_script:
    - echo 'Skipping login'
  stage: build
  services:
  - docker:18.06.3-dind
  cache:
    key: api-cache
    paths:
      - api.tar
  artifacts: 
    expire_in: 1 week
    paths: 
      - api.tar
  script: 
    - ls -al
    - '[ -f ./api.tar ] && docker load --input api.tar'
    - docker build -t api:latest -f server/Dockerfile --cache-from api:latest --cache-from node:12-alpine . --target=dev
    - docker save api:latest > api.tar

# dependencies:
#   before_script:
#     - echo 'Skipping login'
#   stage: build
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - node_modules/
#       - client/node_modules
#       - server/node_modules
#   script:
#     - yarn

# build production:
#   services:
#     - docker:18.06.3-dind
#   script:
#     - ./scripts/pipeline/build.sh
#     - docker save $ECR:$CI_COMMIT_SHA > app.tar
#   stage: build
#   artifacts:
#     expire_in: 30 days
#     paths:
#       - app.tar

# build layer deps:
#   stage: build
#   services:
#     - docker:18.06.3-dind
#   script:
#     - cd imageResizer/layer
#     - yarn build
#   artifacts:
#     expire_in: 30 days
#     paths:
#       - imageResizer/layer/
  
test:
  stage: test
  before_script:
    - echo 'Skipping login'
  services:
    - docker:18.06.3-dind
  dependencies:
    - build client
    - build api
  script: 
    # - yarn unit
    # - yarn integration
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker load --input api.tar
    - docker load --input client.tar
    - docker-compose -f docker-compose.e2e.yml up
# deploy:
#   stage: deploy
#   script:
#     - pulumi login s3://carpedalan-pulumi
#     - pulumi up --yes --no-interactive
#   dependencies:
#     - build layer deps