version: '2'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src:delegated
      - ./server:/app/server:delegated
    ports:
      - 3001:3001
      - 9229:9229
    command: yarn start
  pg:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - "5432:5432"

