version: '2.4'

services:

  client:
    stdin_open: true
    image: client:latest
    tty: true
    extends:
      file: docker-compose.base.yml
      service: client
    command: ['yarn', 'test']
    volumes:
      - ./client/jest.config.js:/app/jest.config.js
      - ./client/setupTests.js:/app/setupTests.js
      - ./client/tsconfig.test.json:/app/tsconfig.test.json
    env_file: 
      - .env.ci

