version: '2.3'

services:
  alb:
    extends:
      file: docker-compose.base.yml
      service: alb
    depends_on:
      api: 
        condition: service_healthy

  api:
    extends:
      file: docker-compose.base.yml
      service: api
    depends_on:
      pg:
        condition: service_healthy

  client: 
    extends:
      file: docker-compose.base.yml
      service: client

  pg:
    extends:
      file: docker-compose.base.yml
      service: pg

  pg_test:
    extends:
      file: docker-compose.base.yml
      service: pg_test

  pg_migrate:
    extends:
      file: docker-compose.base.yml
      service: pg_migrate
    depends_on:
      pg_test:
        condition: service_healthy

  sam:
    extends:
      file: docker-compose.base.yml
      service: sam

  aws:
    extends:
      file: docker-compose.base.yml
      service: aws

